repository:
  private: false
  has_issues: true
  has_projects: false
  has_wiki: false
  has_downloads: false
  default_branch: master
  allow_squash_merge: true
  allow_merge_commit: false
  allow_rebase_merge: false
labels:
  - name: "enhancement"
    color: "a2eeef"
  - name: "bug"
    color: "d73a4a"
  - name: "wontfix"
    color: "ffffff"
  - name: "documentation"
    color: "0075ca"
  - name: "stale"
    color: "930191"
  - name: "duplicate"
    color: "cfd3d7"
  - name: "invalid"
    color: "e4e669"
  - name: "more-information-needed"
    color: "dd9c2c"
