repos:
  - repo: local
    hooks:
      - id: update-tracker
        name: "Update Tracker"
        entry: ./update_tracker.py
        language: system
      - id: pylint
        name: pylint
        entry: python3 -m pylint.__main__ -d R0801
        language: system
        types: [python]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.5.0
    hooks:
      - id: check-json
      - id: check-yaml
      - id: trailing-whitespace
