default_config:

logger:
  default: info
  logs:
    custom_components.jq300: debug

# If you need to debug uncomment the line below (doc: https://www.home-assistant.io/integrations/debugpy/)
# debugpy:

jq300:
  username: !secret jq300_username
  password: !secret jq300_password
