#!/bin/sh
# Setups the repository.

# Stop on errors
set -e

cd "$(dirname "$0")/.."
script/bootstrap

pre-commit install

CONFIG=/run/user/$(id -u)/gvfs/smb-share:server=hassio,share=config/
if [ -d "$CONFIG" ] && [ ! -e dev-config ]; then
    ln -s "$CONFIG" dev-config
fi
