#!/bin/sh
# Update application to run for its current checkout.

# Stop on errors
set -e

ROOT="$( cd "$( dirname "${BASH_SOURCE[0]}" )/.." >/dev/null 2>&1 && pwd )"

cd "${ROOT}"
git pull
git submodule update
