---
name: semantic_release

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
        with:
          ref: master
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install python-semantic-release
      - name: Setup Git
        run: |
          git config --global user.name "semantic-release"
          git config --global user.email "semantic-release@GitHub"
      - name: Publish with semantic-release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          DEBUG='*' semantic-release publish
      # Pack the ha-jq300 dir as a zip and upload to the release
      - name: Zip jq300 dir
        run: |
          cd /home/runner/work/ha-jq300/ha-jq300/custom_components/jq300
          zip jq300.zip -r ./
      - name: Set release variable
        run: |
          echo "::set-env name=release_version::`git describe --abbrev=0`"
      - name: Sleep
        # add delay so upload does not kill the release notes from semantic-release
        run: |
          sleep 5
      - name: Upload zip to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: /home/runner/work/ha-jq300/ha-jq300/custom_components/jq300/jq300.zip
          asset_name: jq300.zip
          tag: ${{ env.release_version }}
          overwrite: true
